In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [8]:
iris = load_iris()
X = iris.data
y = iris.target
feature_names = ['sepal_length','sepal_width',
'petal_length', 'petal_width']
X = pd.DataFrame(X, columns=feature_names)
X.head()
y

# splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.2)

#feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#training the naive bayesian model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
#predicting the results
y_pred = classifier.predict(X_test)
y_pred

#confusion matrix and accuracy
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
print(cm)

Accuracy :  0.9666666666666667
[[ 5  0  0]
 [ 0 12  0]
 [ 0  1 12]]
